Info<< "Reading field p\n" << endl;
volScalarField p
(
    IOobject
    (
        "p",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field U\n" << endl;
volVectorField U
(
    IOobject
    (
        "U",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s1" <<endl;
volScalarField s1
(
    IOobject
    (
         "s1",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s2" <<endl;
volScalarField s2
(
    IOobject
    (
         "s2",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s3" <<endl;
volScalarField s3
(
    IOobject
    (
         "s3",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s4" <<endl;
volScalarField s4
(
    IOobject
    (
         "s4",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s5" <<endl;
volScalarField s5
(
    IOobject
    (
         "s5",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s6" <<endl;
volScalarField s6
(
    IOobject
    (
         "s6",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s7" <<endl;
volScalarField s7
(
    IOobject
    (
         "s7",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s8" <<endl;
volScalarField s8
(
    IOobject
    (
         "s8",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s9" <<endl;
volScalarField s9
(
    IOobject
    (
         "s9",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s10" <<endl;
volScalarField s10
(
    IOobject
    (
         "s10",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s11" <<endl;
volScalarField s11
(
    IOobject
    (
         "s11",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s12" <<endl;
volScalarField s12
(
    IOobject
    (
         "s12",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s13" <<endl;
volScalarField s13
(
    IOobject
    (
         "s13",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s14" <<endl;
volScalarField s14
(
    IOobject
    (
         "s14",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s15" <<endl;
volScalarField s15
(
    IOobject
    (
         "s15",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s16" <<endl;
volScalarField s16
(
    IOobject
    (
         "s16",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s17" <<endl;
volScalarField s17
(
    IOobject
    (
         "s17",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s18" <<endl;
volScalarField s18
(
    IOobject
    (
         "s18",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s19" <<endl;
volScalarField s19
(
    IOobject
    (
         "s19",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s20" <<endl;
volScalarField s20
(
    IOobject
    (
         "s20",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s21" <<endl;
volScalarField s21
(
    IOobject
    (
         "s21",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s22" <<endl;
volScalarField s22
(
    IOobject
    (
         "s22",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s23" <<endl;
volScalarField s23
(
    IOobject
    (
         "s23",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s24" <<endl;
volScalarField s24
(
    IOobject
    (
         "s24",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s25" <<endl;
volScalarField s25
(
    IOobject
    (
         "s25",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s26" <<endl;
volScalarField s26
(
    IOobject
    (
         "s26",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s27" <<endl;
volScalarField s27
(
    IOobject
    (
         "s27",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s28" <<endl;
volScalarField s28
(
    IOobject
    (
         "s28",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s29" <<endl;
volScalarField s29
(
    IOobject
    (
         "s29",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s30" <<endl;
volScalarField s30
(
    IOobject
    (
         "s30",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s31" <<endl;
volScalarField s31
(
    IOobject
    (
         "s31",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s32" <<endl;
volScalarField s32
(
    IOobject
    (
         "s32",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s33" <<endl;
volScalarField s33
(
    IOobject
    (
         "s33",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s34" <<endl;
volScalarField s34
(
    IOobject
    (
         "s34",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s35" <<endl;
volScalarField s35
(
    IOobject
    (
         "s35",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s36" <<endl;
volScalarField s36
(
    IOobject
    (
         "s36",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s37" <<endl;
volScalarField s37
(
    IOobject
    (
         "s37",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s38" <<endl;
volScalarField s38
(
    IOobject
    (
         "s38",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s39" <<endl;
volScalarField s39
(
    IOobject
    (
         "s39",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s40" <<endl;
volScalarField s40
(
    IOobject
    (
         "s40",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s41" <<endl;
volScalarField s41
(
    IOobject
    (
         "s41",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s42" <<endl;
volScalarField s42
(
    IOobject
    (
         "s42",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s43" <<endl;
volScalarField s43
(
    IOobject
    (
         "s43",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s44" <<endl;
volScalarField s44
(
    IOobject
    (
         "s44",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s45" <<endl;
volScalarField s45
(
    IOobject
    (
         "s45",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s46" <<endl;
volScalarField s46
(
    IOobject
    (
         "s46",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s47" <<endl;
volScalarField s47
(
    IOobject
    (
         "s47",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s48" <<endl;
volScalarField s48
(
    IOobject
    (
         "s48",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s49" <<endl;
volScalarField s49
(
    IOobject
    (
         "s49",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s50" <<endl;
volScalarField s50
(
    IOobject
    (
         "s50",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s51" <<endl;
volScalarField s51
(
    IOobject
    (
         "s51",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s52" <<endl;
volScalarField s52
(
    IOobject
    (
         "s52",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s53" <<endl;
volScalarField s53
(
    IOobject
    (
         "s53",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s54" <<endl;
volScalarField s54
(
    IOobject
    (
         "s54",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s55" <<endl;
volScalarField s55
(
    IOobject
    (
         "s55",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s56" <<endl;
volScalarField s56
(
    IOobject
    (
         "s56",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s57" <<endl;
volScalarField s57
(
    IOobject
    (
         "s57",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s58" <<endl;
volScalarField s58
(
    IOobject
    (
         "s58",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s59" <<endl;
volScalarField s59
(
    IOobject
    (
         "s59",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s60" <<endl;
volScalarField s60
(
    IOobject
    (
         "s60",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s61" <<endl;
volScalarField s61
(
    IOobject
    (
         "s61",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s62" <<endl;
volScalarField s62
(
    IOobject
    (
         "s62",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s63" <<endl;
volScalarField s63
(
    IOobject
    (
         "s63",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s64" <<endl;
volScalarField s64
(
    IOobject
    (
         "s64",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s65" <<endl;
volScalarField s65
(
    IOobject
    (
         "s65",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s66" <<endl;
volScalarField s66
(
    IOobject
    (
         "s66",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s67" <<endl;
volScalarField s67
(
    IOobject
    (
         "s67",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s68" <<endl;
volScalarField s68
(
    IOobject
    (
         "s68",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s69" <<endl;
volScalarField s69
(
    IOobject
    (
         "s69",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s70" <<endl;
volScalarField s70
(
    IOobject
    (
         "s70",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s71" <<endl;
volScalarField s71
(
    IOobject
    (
         "s71",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s72" <<endl;
volScalarField s72
(
    IOobject
    (
         "s72",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s73" <<endl;
volScalarField s73
(
    IOobject
    (
         "s73",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s74" <<endl;
volScalarField s74
(
    IOobject
    (
         "s74",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s75" <<endl;
volScalarField s75
(
    IOobject
    (
         "s75",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s76" <<endl;
volScalarField s76
(
    IOobject
    (
         "s76",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s77" <<endl;
volScalarField s77
(
    IOobject
    (
         "s77",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s78" <<endl;
volScalarField s78
(
    IOobject
    (
         "s78",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s79" <<endl;
volScalarField s79
(
    IOobject
    (
         "s79",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s80" <<endl;
volScalarField s80
(
    IOobject
    (
         "s80",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

Info<< "Reading field s81" <<endl;
volScalarField s81
(
    IOobject
    (
         "s81",
         runTime.timeName(),
         mesh,
         IOobject::MUST_READ,
         IOobject::AUTO_WRITE
    ),
    mesh
);

#include "createPhi.H"

    Info<< "Reading transportProperties\n" << endl;

    IOdictionary transportProperties
    (
        IOobject
        (
            "transportProperties",
            runTime.constant(),
            mesh,
            IOobject::MUST_READ,
            IOobject::NO_WRITE
        )
    );

    dimensionedScalar Ds
    (
         transportProperties.lookup("Ds")
    );

    dimensionedScalar Sct
    (
         transportProperties.lookup("Sct")
    );


label pRefCell = 0;
scalar pRefValue = 0.0;
setRefCell(p, pimple.dict(), pRefCell, pRefValue);
mesh.setFluxRequired(p.name());


singlePhaseTransportModel laminarTransport(U, phi);

autoPtr<incompressible::turbulenceModel> turbulence
(
    incompressible::turbulenceModel::New(U, phi, laminarTransport)
);

#include "createMRF.H"
